openapi: 3.0.1
info:
  title: File Upload API
  description: API for uploading files
  version: "1.0.0"
servers:
  - url: http://localhost:8080
paths:
  /upload:
    post:
      summary: Upload a file
      description: Upload a file using multipart/form-data. The request must include a valid Bearer token for authentication.
      operationId: uploadFile
      tags:
        - File Upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to upload
            encoding:
              file:
                contentType: application/octet-stream
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid file input or missing file
          content:
            application/json:
              schema:
                type: string
                example: "No file uploaded!"
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: string
                example: "Unauthorized"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
