version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      monitoring:
        ipv4_address: 172.20.0.10

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      monitoring:
        ipv4_address: 172.20.0.11

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      monitoring:
        ipv4_address: 172.20.0.12

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
